# -*- coding: utf-8 -*-
"""H001_Automated_Insight_Engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ppryx7IPWmQe87m7FtEXqIU6u_ecU4mo
"""



!pip install pandas numpy python-pptx openai

import os

os.makedirs("data", exist_ok=True)
os.makedirs("output", exist_ok=True)

print("Folders ready ✅")

import pandas as pd
import numpy as np
from datetime import datetime

def generate_synthetic_data(output_path: str = "data/synthetic_ads.csv"):
    np.random.seed(42)

    dates = pd.date_range(end=datetime.today(), periods=30)
    campaigns = ["Brand_US", "Brand_IN", "Remarketing", "New_Users"]
    channels = ["Google", "Meta", "Display"]
    countries = ["US", "IN"]

    rows = []

    for date in dates:
        for campaign in campaigns:
            impressions = np.random.randint(2000, 15000)
            ctr = np.random.uniform(0.01, 0.05)
            clicks = int(impressions * ctr)
            cpc = np.random.uniform(3, 20)
            spend = clicks * cpc
            conv_rate = np.random.uniform(0.02, 0.08)
            conversions = int(clicks * conv_rate)
            revenue_per_conv = np.random.uniform(150, 600)
            revenue = conversions * revenue_per_conv

            rows.append([
                date.date(),
                campaign,
                np.random.choice(channels),
                np.random.choice(countries),
                impressions,
                clicks,
                round(spend, 2),
                conversions,
                round(revenue, 2),
            ])

    df = pd.DataFrame(
        rows,
        columns=[
            "date",
            "campaign",
            "channel",
            "country",
            "impressions",
            "clicks",
            "spend",
            "conversions",
            "revenue",
        ],
    )

    df.to_csv(output_path, index=False)
    print(f"Synthetic data generated at {output_path}")

generate_synthetic_data()
import pandas as pd
import numpy as np

def generate_foot_traffic(path="data/foot_traffic.csv"):
    ads = pd.read_csv("data/synthetic_ads.csv", parse_dates=["date"])
    unique_dates = ads["date"].unique()

    rows = []
    for d in unique_dates:
        foot_traffic = np.random.randint(800, 5000)
        rows.append([d, foot_traffic])

    df = pd.DataFrame(rows, columns=["date", "foot_traffic"])
    df.to_csv(path, index=False)
    print(f"Foot traffic data generated at {path}")

generate_foot_traffic()

def analyze_data(ads_path: str):
    ads = pd.read_csv(ads_path, parse_dates=["date"])
    ft = pd.read_csv("data/foot_traffic.csv", parse_dates=["date"])

    # Merge digital + physical data
    df = pd.merge(ads, ft, on="date", how="left")

    total_spend = df["spend"].sum()
    total_revenue = df["revenue"].sum()
    total_impressions = df["impressions"].sum()
    total_clicks = df["clicks"].sum()
    total_conversions = df["conversions"].sum()

    summary = {
        "total_spend": float(total_spend),
        "total_revenue": float(total_revenue),
        "total_impressions": int(total_impressions),
        "total_clicks": int(total_clicks),
        "total_conversions": int(total_conversions),
        "roas": float(total_revenue / total_spend) if total_spend > 0 else 0.0,
        "ctr": float(total_clicks / total_impressions) if total_impressions > 0 else 0.0,
        "cvr": float(total_conversions / total_clicks) if total_clicks > 0 else 0.0,
        "avg_foot_traffic": float(df["foot_traffic"].mean()),
        "spend_vs_foot_corr": float(df["spend"].corr(df["foot_traffic"]))
        if df["foot_traffic"].notna().any() else 0.0,
    }

    top_campaigns = (
        df.groupby("campaign")[["spend", "revenue", "impressions", "clicks"]]
        .sum()
        .reset_index()
        .sort_values("spend", ascending=False)
        .head(5)
    )

    analytics_payload = {
        "summary": summary,
        "top_campaigns": top_campaigns.to_dict(orient="records"),
    }

    return analytics_payload

analytics_payload = analyze_data("data/synthetic_ads.csv")
analytics_payload

import os
import json
import textwrap

try:
    from openai import OpenAI
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
except Exception:
    client = None

def generate_insights(analytics_payload: dict) -> str:
    # If no API key or client, return a simple fake narrative (still valid for demo)
    if not os.getenv("OPENAI_API_KEY") or client is None:
        s = analytics_payload["summary"]
        return textwrap.dedent(f"""
        • Total spend was approximately {s['total_spend']:.0f} with revenue of {s['total_revenue']:.0f}, delivering a ROAS of {s['roas']:.2f}.
        • The account generated {s['total_impressions']} impressions and {s['total_clicks']} clicks, with a CTR of {s['ctr']*100:.2f}%.
        • There were {s['total_conversions']} conversions, with a CVR of {s['cvr']*100:.2f}% across all campaigns.
        • Spend is distributed across a small number of key campaigns, enabling focused optimization.

        Key Risks / Issues:
        • Performance is concentrated in a few top campaigns, increasing dependency risk.
        • Some campaigns may be driving spend without proportional revenue.
        • Conversion efficiency may degrade if volume scales without optimization.

        Recommended Actions:
        • Reallocate budget towards campaigns with above-average ROAS and strong CTR.
        • Pause or limit campaigns with high spend but weak revenue or low CVR.
        • Test new creatives and audiences in the best-performing channels to scale results.
        """).strip()

    prompt = f"""
You are a senior AdTech performance marketer.

You are given aggregated campaign metrics as JSON:

{json.dumps(analytics_payload, indent=2)}

From this, write:

1. A 4–6 bullet Executive Summary.
2. 3 bullet "Key Risks / Issues".
3. 3 bullet "Recommended Actions for next week".

Be concise, use specific numbers where useful, and write in clear business language.
"""

    resp = client.chat.completions.create(
        model="gpt-4.1-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.4,
    )

    return resp.choices[0].message.content

insights_text = generate_insights(analytics_payload)
print(insights_text)

import matplotlib.pyplot as plt

def export_spend_trend_chart():
    df = pd.read_csv("data/synthetic_ads.csv", parse_dates=["date"])
    daily = df.groupby("date")[["spend"]].sum().reset_index()

    plt.figure(figsize=(8, 4))
    plt.plot(daily["date"], daily["spend"])
    plt.title("Daily Spend Trend")
    plt.xlabel("Date")
    plt.ylabel("Spend")
    plt.tight_layout()
    plt.savefig("output/spend_trend.png")
    plt.close()

export_spend_trend_chart()

from pptx import Presentation
from pptx.util import Inches

def build_ppt(insights_text: str, analytics_payload: dict, output_path: str = "output/Automated_Report.pptx"):
    prs = Presentation()

    # Slide 1 – Title
    slide1 = prs.slides.add_slide(prs.slide_layouts[0])
    slide1.shapes.title.text = "Weekly Performance Report"
    slide1.placeholders[1].text = "Automated Insight Engine – GroundTruth Hackathon 2025"

    # Slide 2 – Executive Insights
    slide2 = prs.slides.add_slide(prs.slide_layouts[1])
    slide2.shapes.title.text = "Executive Insights"
    slide2.placeholders[1].text = insights_text

    # Slide 3 – Key Metrics
    s = analytics_payload["summary"]
    slide3 = prs.slides.add_slide(prs.slide_layouts[1])
    slide3.shapes.title.text = "Key Metrics Snapshot"
    slide3.placeholders[1].text = (
        f"Total Spend: {s['total_spend']:.2f}\n"
        f"Total Revenue: {s['total_revenue']:.2f}\n"
        f"ROAS: {s['roas']:.2f}\n"
        f"CTR: {s['ctr']*100:.2f}%\n"
        f"CVR: {s['cvr']*100:.2f}%\n"
        f"Avg Foot Traffic: {s['avg_foot_traffic']:.0f}\n"
        f"Spend–Footfall Corr: {s['spend_vs_foot_corr']:.2f}"
    )

    # Slide 4 – Trend Chart
    slide4 = prs.slides.add_slide(prs.slide_layouts[5])
    slide4.shapes.title.text = "Daily Spend Trend"
    slide4.shapes.add_picture(
        "output/spend_trend.png",
        Inches(1),
        Inches(1.5),
        width=Inches(8),
    )

    prs.save(output_path)
    print(f"PPT generated at {output_path}")

build_ppt(insights_text, analytics_payload)

from google.colab import files

files.download("output/Automated_Report.pptx")